variavel = input('Digite a variavel:')
print('O tipo primitivo desse valor é ', type(variavel))
print('Só tem espaços? ', variavel.isspace())
print('É um número?', variavel.isnumeric())
print('É alfabético? ', variavel.isalpha())
print('É alfanumérico? ', variavel.isalnum())
print('Está em minúscula? ', variavel.islower())
print('Está em maiúsculas? ', variavel.isupper())
print('Está capitalizada? ', variavel.istitle())